export default {
  managerPrograms: 'manager/programs/',
  managerProgramsUUID: 'manager/programs/$uuid/',
  managerReminders: 'manager/reminders/',
  managerRemindersUUID: 'manager/reminders/$uuid/',
  managerReminderSettingsUUID: 'manager/reminder-settings/$uuid/',
  managerReminderSenderTypes: 'commons/reminder-sender-types/',
  managerReminderPeriods: 'manager/reminder-periods/$uuid/',
  managerProgramAcceptors: 'manager/program-acceptors/',
  managerProgramAcceptorsUUID: 'manager/program-acceptors/$uuid/',
  managerCards: 'manager/cards/',
  managerCardsUUID: 'manager/cards/$uuid',
  managerCardTypes: 'manager/card-types/',
  managerCardTypesID: 'manager/card-types/$id',
  managerCardImages: 'commons/images/',
  managerCardValues: 'manager/card-values/',
  managerValueTypes: 'commons/value-types/',
  managerCardExpiriesUUID: 'manager/card-expiries/$uuid',
  managerCurrencies: 'commons/currencies/',
  managerCardTypePrices: 'manager/card-type-prices/',

  commonsStatusTypes: 'commons/status-types/',
  commonsStatuses: 'commons/statuses/',
}
