export default {
  promo: 'promo',
  signup: 'signup',
  signupStepOne: 'signup/step_one/',
  signupResend: 'signup/resend',
  signupCode: 'signup/code',
  signupComplete: 'signup/complete',
  password: 'password',
  passwordChange: 'password/change',
  passwordCode: 'password/code',
  login: 'login',
  tokenCheck: 'token/check',
  tokenRefresh: 'token/refresh',
  tokenInvalidate: 'token/invalidate',
  profile: 'profile',
  profileLoginHistory: 'profile/login-history',
  profileAvatar: 'profile/avatar',
  acceptorInvite: 'acceptor-invite',
  publicProfile: 'users/$uuid',
  users: 'users/',
}
